app/src/main/java/com/mtesitoo/HomeActivity.java
app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java
app/src/main/res/layout/activity_my_profile.xml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Seller.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/RegistrationRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/RegistrationResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/SellerResponse.java

- profile screen now displaying user details and profile image
- changed Seller model include additional address line provided for on
the My Profile screen of the web app
- changed  number of parameters in Seller constructor to pass in some
values from the profile that were missing, with associated changes to
the calls
- removed payment details from profile view after discussion with David
on 14/7/2016
- removed parseResponse from RegistrationResponse rather than amend the
list of values in call to Seller() - seems like it’s not being called…

Display user profile details

---

app/app.iml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/mtesitoo/LoginActivity.java
app/src/main/java/com/mtesitoo/RegistrationActivity.java
app/src/main/java/com/mtesitoo/adapter/OrderListAdapter.java
app/src/main/java/com/mtesitoo/fragment/OrderDetailFragment.java
app/src/main/java/com/mtesitoo/fragment/OrderFragment.java
app/src/main/java/com/mtesitoo/helper/FormatHelper.java
app/src/main/res/layout/order_list_item.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_activity_registration.xml
app/src/main/res/values/styles.xml
libs/mtesitoo-backend-api/mtesitoo-backend-api.iml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Order.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/url/VendorOrdersURL.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/LoginResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderResponse.java
libs/mtesitoo-backend-api/src/main/res/values/strings_api_resources.xml

- Added the ability to read pending orders for a vendor.
- For each order, show customer name, total price, order status and the date when the order was placed.
This is what the UI looks like. Let me know if there is any other fields that you would like to see. For instance, I wasn't sure whether to add telephone number here or not.

View list of pending orders

---

app/src/main/java/com/mtesitoo/adapter/OrderListAdapter.java
app/src/main/java/com/mtesitoo/adapter/OrderProductListAdapter.java
app/src/main/java/com/mtesitoo/fragment/OrderDetailFragment.java
app/src/main/res/layout/activity_order_fragment_detail.xml
app/src/main/res/layout/order_list_item.xml
app/src/main/res/layout/order_product_list_item.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Order.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/OrderProduct.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/url/VendorOrderDetailsURL.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/url/VendorOrdersURL.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderDetailsResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/logic/IOrderRequest.java

If you click on an order, you should be able to view additional data such as customer details, details of each product.
All the info is now there. The next code drop will mostly focus on UI changes and refactoring.

View detailed information for an order (products and customer details)

---

app/src/main/java/com/mtesitoo/adapter/OrderListAdapter.java
app/src/main/java/com/mtesitoo/adapter/OrderProductListAdapter.java
app/src/main/java/com/mtesitoo/fragment/OrderDetailFragment.java
app/src/main/res/layout/order_product_list_item.xml
app/src/main/res/values/strings.xml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Order.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/OrderProduct.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/OrderStatus.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderDetailsResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderResponse.java
libs/mtesitoo-backend-api/src/main/res/values/strings_api_resources.xml
libs/mtesitoo-backend-api/src/main/res/values/strings_order_status.xml

- React to API changes introduced - when reading orders from the server, there will now be a total_count field in the json response object
- When viewing details about an order, the product status is now shown for each product. This is subject to change due to current discussions surrounding the complexity of having different order status and product status.

Seller order history

---

app/src/main/java/com/mtesitoo/RegistrationActivity.java
app/src/main/java/com/mtesitoo/model/RegistrationWizard.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/RegistrationResponse.java

Fixes broken new user registration #25.
(empty strings for city, state & description which are not requested in wizard)

Add missing fields in Seller constructor call.

---

app/src/main/java/com/mtesitoo/adapter/OrderListAdapter.java
app/src/main/java/com/mtesitoo/adapter/OrderProductListAdapter.java
app/src/main/java/com/mtesitoo/fragment/EditOrderFragment.java
app/src/main/java/com/mtesitoo/fragment/OrderDetailFragment.java
app/src/main/java/com/mtesitoo/fragment/OrderFragment.java
app/src/main/res/layout/activity_edit_order_fragment.xml
app/src/main/res/layout/order_product_list_item.xml
app/src/main/res/menu/menu_edit_order.xml
app/src/main/res/menu/menu_order.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_activity_home.xml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Order.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/OrderProduct.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/url/VendorOrderDetailsURL.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderDetailsResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/OrderRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/logic/IOrderRequest.java
libs/mtesitoo-backend-api/src/main/res/values/strings_api_resources.xml

Users cannot change the status for all orders at once.
They can view all the products within an order. Products can be edited one at a time.

First pass at implementing solution for changing statuses one order product at a time

---

libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProductRequest.java

Creating against `pt-forgot-password` for better visibility on changes made.

fixed crash when clicking done in product edit ui

---

circle.yml

Circleci issue fixed

---

app/src/main/java/com/mtesitoo/RegisterActivity.java

Business name should be "<firstname> <lastname>" rather than just "<firstname>".

---

app/app.iml
app/src/main/AndroidManifest.xml
app/src/main/java/com/mtesitoo/AddProductActivity2.java
app/src/main/java/com/mtesitoo/Constants.java
app/src/main/java/com/mtesitoo/HomeActivity.java
app/src/main/java/com/mtesitoo/RegisterActivity.java
app/src/main/java/com/mtesitoo/fragment/ProductDetailEditFragment.java
app/src/main/java/com/mtesitoo/fragment/ProductDetailFragment.java
app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Product.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProductDetailResponse.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProductRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProductResponse.java

Fixes: 
https://github.com/projectwife/mtesitoo-android/issues/85
https://github.com/projectwife/mtesitoo-android/issues/92
https://github.com/projectwife/mtesitoo-android/issues/93
https://github.com/projectwife/mtesitoo-android/issues/94
https://github.com/projectwife/mtesitoo-android/issues/103
https://github.com/projectwife/mtesitoo-android/issues/104

Fixes github issues: 85, 92, 93, 94, 103 and 104

---

app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java
app/src/main/res/layout/content_profile.xml
app/src/main/res/values/strings.xml

#139 Removing unused fields

---

app/src/main/res/layout/content_profile.xml

As agreed with @david-r-edgar in #82, v1 will not allow users to change their email address. This pull request will disable the editing option for the email EditText.

Disabling email EditText

---

app/src/main/java/com/mtesitoo/AddProductActivity2.java
app/src/main/java/com/mtesitoo/fragment/ProductFragment.java

Added a LocalBroadcastReceiver to notify the parent fragment after the image has downloaded to trigger a product list refresh.

Fixed the thumbnail loading issue

---

app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java
app/src/main/res/layout/fragment_profile.xml

Profile Screen: preview mode. Stopping EditText from gaining focus 

---

app/src/main/res/values/strings.xml
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/cache/ZoneCache.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ZoneRequest.java
libs/mtesitoo-backend-api/src/main/res/values/strings.xml

Improving list of regions cache

---

app/src/main/java/com/mtesitoo/Constants.java
app/src/main/java/com/mtesitoo/HomeActivity.java
app/src/main/java/com/mtesitoo/LoginActivity.java
app/src/main/java/com/mtesitoo/fragment/OrderFragment.java
app/src/main/java/com/mtesitoo/fragment/ProductFragment.java
app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java
app/src/main/java/com/mtesitoo/helper/UriAdapter.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/MultipartRequest.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/ProfilePicture.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/model/Seller.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProfileThumbnailResponse.java

Updating profile object after successful request

---

app/src/main/java/com/mtesitoo/HomeActivity.java
app/src/main/java/com/mtesitoo/fragment/ProfileFragment.java

Placing profile picture next to name on menu

---

app/src/main/java/com/mtesitoo/LoginActivity.java

Fixed issue where the progress overlay didn't dismiss when the login failed.

Bug fix to handle error cases in login correctly.

---

app/src/main/java/com/mtesitoo/AddProductActivity.java

Fixed a crash due to null execption when checking length of a URI List

Fix a crash on Submit Product

---

libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/ExifUtil.java
libs/mtesitoo-backend-api/src/main/java/com/mtesitoo/backend/service/ProductRequest.java

Fix the image orientation issue in product image thumbnails.
The code can be further cleaned up by pushing the changes from ProductRequest class to ExifUtil class

Image orientation fix
